name             'jenkins_with_chef'
maintainer       'SS_TRAINING_CENTER_LV-164-DevOps'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures jenkins_with_chef'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
depends 'jenkins', '~> 2.4.1'
depends 'apt'
depends 'git'
depends 'maven'
depends 'wlp'
